# Active Spring profiles
spring.profiles.active: production  
       
logging:
  level:
    root: error
    org.springframework: warn
    it.applicazione: info
  file: C:/dev/home/applicazione/myapplication.log


spring:
  mail:
    host: mail.xxxxx.it
    port: 587
    username: a.xxxxxx@xxxxx.it
    password: xxxxxx
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

  # su console h2 imposta   JDBC URL: jdbc:h2:C:\dev\home\applicazione\db
  datasource:
    url: jdbc:h2:file:C:/dev/home/applicazione/db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    # http://localhost:80/applicazione/h2 
    
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true 
    #hql 
    #properties:
      #hibernate:
        #show_sql: true
        #use_sql_comments: true
        #format_sql: true
        
  h2:
    console:
      path: /h2
      enabled: true
     
      
configuration:
  applicazione:
    admin: admin
    admin-pwd: aaaaaa
    destinatari:
    - a.xxxxxx@xxxxx.it
    - xxxxxxxo@hotmail.it

spring.thymeleaf.mode: HTML
  
server:
  port: 80
  compression.enabled: true
  servlet:
    context-path: /applicazione
    session:
      store-dir: C:/dev/home/applicazione/sessionStore
        
  tomcat.basedir: C:/dev/home/applicazione/tomcat
  tomcat.accesslog.enabled: true
  tomcat.accesslog.pattern: /%t %a "%r" %s (%D ms)
  
# Internationalization
spring.messages.basename: messages/messages

